print("I like cookies")
print("Hello, nerd - Remote")
print("Cats are better than dogs")
print("Sometimes I think")
print("Hello, nerd - Local")
print("Sometimes I'm stupid")
print("Sometimes I realize I'm stupid")
print("Added during merge")
print("Remote end")
print("Local end")
print("Working from dev branch")
print("Never gonna give you up, never gonna let you down")
